//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int CardID { get; set; }
        public string UserID { get; set; }
        public string CardNumber { get; set; }
        public string CardHolder { get; set; }
        public string CardMonth { get; set; }
        public string CardYear { get; set; }
        public string Ballance { get; set; }
    }
}
