//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string AccountID { get; set; }
        public System.DateTime DOJ { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public string Phone { get; set; }
        public string ConfirmationDOC { get; set; }
        public string UserAddress { get; set; }
        public string UserProfile { get; set; }
        public string UserPass { get; set; }
        public string WalletID { get; set; }
    }
}
